### ISSUE TITLE
Change Color Frame schema from GRB to RGB?

### ISSUE THREAD

**Issue by Koopzington** [arvydas/BlinkStickDotNet#2]
I just tried out the setColors() method and got a bit confused at first.
After looking in the wiki i saw that the order you have to use in the color frame was GRB instead of RGB and i wondered if it could be possible to change it to RGB to make the programming a bit more comfortable.

**Comment by arvydas** [comment]
All API implementations use the GRB, because this is how LEDs accept data. There is no point in converting the data to RGB format inside the microcontroller (MCU), because it's limited to only 512 Bytes of RAM and it would be a waste resources on the device. It can be accomplished by an extension method.

```csharp
	public static class ExcensionMethods
	{
		/// <summary>
		/// Send a packet of data to LEDs
		/// </summary>
		/// <param name="channel">Channel (0 - R, 1 - G, 2 - B)</param>
		/// <param name="reportData">Report data must be a byte array in the following format: [r0, g0, b0, r1, g1, b1, r2, g2, b2 ...]</param>
		public static void SetColorsRGB(this BlinkStick led, byte channel, byte[] colorData) 
		{
			//initialize new data array
			byte[] data = new byte[colorData.Length];

			for (int i = 0; i < colorData.Length; i++) {

				if (i % 3 == 0 && i + 1 < colorData.Length) { //Swap G -> R
					data [i + 1] = colorData [i];
				}
				else if (i % 3 == 1) //Swap R -> G
				{
					data[i - 1] = colorData[i];
				}
				else //Copy B
				{
					data[i] = colorData[i];
				}
			}

			//Send the converted GRB report
			led.SetColors (channel, data);
		}
	}
```

Then you can call the function SetColorsRGB with the array of bytes in [R,G,B] format just like the [SetColors](http://arvydas.github.io/BlinkStickDotNet/class_blink_stick_dot_net_1_1_blink_stick.html#a7ec384e7e617ceb3acdfab7e1e7c631a) function:

```csharp
led.SetColorsRGB(0, new byte[] { 
	255, 0, 0, 
	0, 255, 0,
	0, 0, 255});
```

Hope this helps. Please let me know if you need any further assistance.
